services:
  app:
    build:
      context: "./web"
      dockerfile: Dockerfile-dev
    container_name: app-next
    ports:
      - "3000:3000"
    restart: unless-stopped
  
  ws-server:
    build:
      context: "./ws-server"
      dockerfile: Dockerfile
    container_name: ws-server
    ports:
      - "8080:8080"
    restart: unless-stopped

  peerjs-server:
    build:
      context: "./peerjs-server"
      dockerfile: Dockerfile
    container_name: peerjs-server
    ports:
      - "9000:9000"
    restart: unless-stopped