FROM node:20.18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

ENV DATABASE_URL="file:./dev.db"
ENV NEXT_PUBLIC_SOCKET_SERVER_URL="http://localhost:8080"
ENV NEXT_PUBLIC_AGENT_SERVER_URL="http://localhost:8000/save_audio/"
ENV NEXT_TELEMETRY_DISABLED 1

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["npm", "run", "dev"]

